#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-directory-maven-plugin
Version  : 0.3.1
Release  : 1
URL      : https://github.com/jdcasey/directory-maven-plugin/archive/directory-maven-plugin-0.3.1.tar.gz
Source0  : https://github.com/jdcasey/directory-maven-plugin/archive/directory-maven-plugin-0.3.1.tar.gz
Source1  : https://repo1.maven.org/maven2/org/commonjava/maven/plugins/directory-maven-plugin/0.1/directory-maven-plugin-0.1.jar
Source2  : https://repo1.maven.org/maven2/org/commonjava/maven/plugins/directory-maven-plugin/0.1/directory-maven-plugin-0.1.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-directory-maven-plugin-data = %{version}-%{release}
Requires: mvn-directory-maven-plugin-license = %{version}-%{release}

%description
Directory Plugin for Maven
==========================
Disclaimer
----------
This plugin is for use in very specific situations!

%package data
Summary: data components for the mvn-directory-maven-plugin package.
Group: Data

%description data
data components for the mvn-directory-maven-plugin package.


%package license
Summary: license components for the mvn-directory-maven-plugin package.
Group: Default

%description license
license components for the mvn-directory-maven-plugin package.


%prep
%setup -q -n directory-maven-plugin-directory-maven-plugin-0.3.1

%build

%install
mkdir -p %{buildroot}/usr/share/package-licenses/mvn-directory-maven-plugin
cp LICENSE %{buildroot}/usr/share/package-licenses/mvn-directory-maven-plugin/LICENSE
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/commonjava/maven/plugins/directory-maven-plugin/0.1
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/commonjava/maven/plugins/directory-maven-plugin/0.1/directory-maven-plugin-0.1.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/commonjava/maven/plugins/directory-maven-plugin/0.1
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/commonjava/maven/plugins/directory-maven-plugin/0.1/directory-maven-plugin-0.1.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/commonjava/maven/plugins/directory-maven-plugin/0.1/directory-maven-plugin-0.1.jar
/usr/share/java/.m2/repository/org/commonjava/maven/plugins/directory-maven-plugin/0.1/directory-maven-plugin-0.1.pom

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/mvn-directory-maven-plugin/LICENSE
